import re

def escape_markdown_v2(text: str) -> str:
    """Escapes strings for Telegram MarkdownV2"""
    # Characters that need escaping in Telegram's MarkdownV2
    escape_chars = r'_*[]()~`>#+-=|{}.!'
    return re.sub(f'([{re.escape(escape_chars)}])', r'\\\1', text)

def escape_markdown_v2_reserving_format(text: str) -> str:
    """Escapes characters for MarkdownV2 while preserving basic formatting (*, _, `, [, ]).
    Useful when rendering text generated by an LLM that includes formatting.
    """
    # 1. Convert Markdown unordered lists ("- " or "* ") to Telegram bullet points ("• ")
    text = re.sub(r'(?m)^(\s*)([-*])\s+', r'\1• ', text)
    
    # 2. Convert correct Markdown bold (**text**) to Telegram bold (*text*)
    text = re.sub(r'\*\*(.+?)\*\*', r'*\1*', text, flags=re.DOTALL)
    
    # 3. Convert correct Markdown italic (__text__) to Telegram italic (_text_)
    text = re.sub(r'__(.+?)__', r'_\1_', text, flags=re.DOTALL)

    # 4. Check balanced * and _ and ` 
    # If unbalanced, we just escape ALL of them to ensure message delivery.
    if text.count('*') % 2 != 0:
        text = text.replace('*', r'\*')
    if text.count('_') % 2 != 0:
        text = text.replace('_', r'\_')
    if text.count('`') % 2 != 0:
        text = text.replace('`', r'\`')

    # 5. Escape characters safe to escape blindly without breaking basic bold/italic/links
    escape_chars = r'.!+-=|{}#>~()'
    # Wait, escaping () will break [Text](URL)!
    # Let's escape only those not part of a markdown link.
    # To be safe, we'll stick to the original set and add (), but avoid breaking links.
    # A simpler way: just escape the missing ones that cause crashes.
    escape_chars = r'.!+-=|{}#>~'
    escaped = re.sub(f'([{re.escape(escape_chars)}])', r'\\\1', text)
    
    # Fix parentheses: escape ( and ) ONLY if not immediately following a string like `](`
    # Also escape [] if not part of a link? Too complex. For now, just fix the ones that are standalone.
    escaped = re.sub(r'(?<!\])\(', r'\(', escaped)
    escaped = re.sub(r'\)(?!\s*\[)', r'\)', escaped)  # Close parenthesis that isn't before another link maybe?
    # Actually, escaping ) blindly is mostly fine UNLESS it's the end of a link.
    # Let's just fix the parenthesis conservatively. 
    escaped = escaped.replace('(', r'\(').replace(')', r'\)')
    # Restore links
    escaped = re.sub(r'\[([^\]]+)\]\\\(([^)]+)\\\)', r'[\1](\2)', escaped)

    return escaped

def escape_markdown_v2_code(text: str) -> str:
    """Escapes code blocks for Telegram MarkdownV2 (only \ and ` need escaping)"""
    return text.replace('\\', '\\\\').replace('`', '\\`')

def truncate_text(text: str, max_length: int = 4050, suffix: str = '... [truncated]') -> str:
    """Truncates text safely ensuring we don't exceed Telegram's limit."""
    if len(text) <= max_length:
        return text
    
    return text[:max_length - len(suffix)] + suffix
