"""Increase vector size to 1536 for OpenAI

Revision ID: 8d7831237358
Revises: 3a740107fbfd
Create Date: 2026-03-12 23:56:01.928527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '8d7831237358'
down_revision: Union[str, None] = '3a740107fbfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('output_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_files_task_id'), 'output_files', ['task_id'], unique=False)
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('approvals', 'action_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('approvals', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('approvals', 'preview_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('approvals', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_index(op.f('idx_approvals_status'), table_name='approvals')
    op.drop_index(op.f('idx_approvals_task'), table_name='approvals')
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_index(op.f('ix_approvals_task_id'), 'approvals', ['task_id'], unique=False)
    op.alter_column('cache', 'prompt_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('cache', 'prompt_preview',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('cache', 'response',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('cache', 'model_used',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('cache_prompt_hash_key'), 'cache', type_='unique')
    op.drop_index(op.f('idx_cache_expires'), table_name='cache')
    op.drop_index(op.f('idx_cache_hash'), table_name='cache')
    op.create_index(op.f('ix_cache_expires_at'), 'cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cache_prompt_hash'), 'cache', ['prompt_hash'], unique=True)
    op.alter_column('conversations', 'session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('conversations', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('conversations', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_conversations_session'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_timestamp'), table_name='conversations')
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversations_timestamp'), 'conversations', ['timestamp'], unique=False)
    op.alter_column('facts', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('facts', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('facts', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('facts', 'context',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('facts', 'confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('facts', 'source_session',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_facts_category'), table_name='facts')
    op.drop_index(op.f('idx_facts_key'), table_name='facts')
    op.create_index(op.f('ix_facts_category'), 'facts', ['category'], unique=False)
    op.create_index(op.f('ix_facts_key'), 'facts', ['key'], unique=False)
    op.alter_column('memory_embeddings', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.execute("TRUNCATE TABLE memory_embeddings")
    op.alter_column('memory_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.alter_column('memory_embeddings', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('memory_embeddings', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_memory_type'), table_name='memory_embeddings')
    op.create_index(op.f('ix_memory_embeddings_type'), 'memory_embeddings', ['type'], unique=False)
    op.alter_column('output_history', 'sequence_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_output_history_task_id'), 'output_history', ['task_id'], unique=False)
    op.drop_constraint(op.f('output_history_task_id_fkey'), 'output_history', type_='foreignkey')
    op.create_foreign_key(None, 'output_history', 'tasks', ['task_id'], ['id'])
    op.alter_column('scheduled_jobs', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('scheduled_jobs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'schedule_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('scheduled_jobs', 'schedule_value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('scheduled_jobs', 'task_template',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('scheduled_jobs', 'approval_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'each_time'::text"))
    op.drop_index(op.f('idx_scheduled_jobs_enabled'), table_name='scheduled_jobs')
    op.drop_index(op.f('idx_scheduled_jobs_next_run'), table_name='scheduled_jobs')
    op.create_index(op.f('ix_scheduled_jobs_enabled'), 'scheduled_jobs', ['enabled'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_next_run'), 'scheduled_jobs', ['next_run'], unique=False)
    op.alter_column('summaries', 'session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('summaries', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_summaries_session'), table_name='summaries')
    op.create_index(op.f('ix_summaries_session_id'), 'summaries', ['session_id'], unique=False)
    op.alter_column('system_state', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('system_state', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tasks', 'output_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tasks', 'output_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'agent_used',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'model_used',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'checkpoint',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_tasks_created'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_created'), 'tasks', ['created_at'], unique=False)
    op.alter_column('tasks', 'checkpoint',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tasks', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'model_used',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'agent_used',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'output_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'output_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tasks', 'input_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('system_state', 'value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('system_state', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_summaries_session_id'), table_name='summaries')
    op.create_index(op.f('idx_summaries_session'), 'summaries', ['session_id'], unique=False)
    op.alter_column('summaries', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('summaries', 'session_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_scheduled_jobs_next_run'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_enabled'), table_name='scheduled_jobs')
    op.create_index(op.f('idx_scheduled_jobs_next_run'), 'scheduled_jobs', ['next_run'], unique=False)
    op.create_index(op.f('idx_scheduled_jobs_enabled'), 'scheduled_jobs', ['enabled'], unique=False)
    op.alter_column('scheduled_jobs', 'approval_mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'each_time'::text"))
    op.alter_column('scheduled_jobs', 'task_template',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scheduled_jobs', 'schedule_value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('scheduled_jobs', 'schedule_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('scheduled_jobs', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'output_history', type_='foreignkey')
    op.create_foreign_key(op.f('output_history_task_id_fkey'), 'output_history', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_output_history_task_id'), table_name='output_history')
    op.alter_column('output_history', 'sequence_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_memory_embeddings_type'), table_name='memory_embeddings')
    op.create_index(op.f('idx_memory_type'), 'memory_embeddings', ['type'], unique=False)
    op.alter_column('memory_embeddings', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('memory_embeddings', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('memory_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    op.alter_column('memory_embeddings', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_facts_key'), table_name='facts')
    op.drop_index(op.f('ix_facts_category'), table_name='facts')
    op.create_index(op.f('idx_facts_key'), 'facts', ['key'], unique=False)
    op.create_index(op.f('idx_facts_category'), 'facts', ['category'], unique=False)
    op.alter_column('facts', 'source_session',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('facts', 'confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('facts', 'context',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('facts', 'value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('facts', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('facts', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_conversations_timestamp'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.create_index(op.f('idx_conversations_timestamp'), 'conversations', ['timestamp'], unique=False)
    op.create_index(op.f('idx_conversations_session'), 'conversations', ['session_id'], unique=False)
    op.alter_column('conversations', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('conversations', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('conversations', 'session_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_cache_prompt_hash'), table_name='cache')
    op.drop_index(op.f('ix_cache_expires_at'), table_name='cache')
    op.create_index(op.f('idx_cache_hash'), 'cache', ['prompt_hash'], unique=False)
    op.create_index(op.f('idx_cache_expires'), 'cache', ['expires_at'], unique=False)
    op.create_unique_constraint(op.f('cache_prompt_hash_key'), 'cache', ['prompt_hash'])
    op.alter_column('cache', 'model_used',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cache', 'response',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('cache', 'prompt_preview',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cache', 'prompt_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_approvals_task_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.create_index(op.f('idx_approvals_task'), 'approvals', ['task_id'], unique=False)
    op.create_index(op.f('idx_approvals_status'), 'approvals', ['status'], unique=False)
    op.alter_column('approvals', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('approvals', 'preview_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('approvals', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('approvals', 'action_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_output_files_task_id'), table_name='output_files')
    op.drop_table('output_files')
    # ### end Alembic commands ###
